import test from 'node:test';import assert from 'node:assert/strict';import {createRequire} from 'node:module';import {createHash} from 'node:crypto';import fs from 'node:fs';const require=createRequire(import.meta.url),e=require('./gold-daily-prototypes.js'),loop=require('./gold-daily-loop.js');
const ids=['gold_return_time_v1','gold_serve_quality_v1','gold_pattern_clue_v1'];
// 21 Sep repair: Return Position D3 explicitly carries its slower pace ratio.
// This is a change detector, not coaching or visual approval; timing has separate tests.
test('prior eighteen definitions match the explicit repair candidate',()=>{const old=e.challenges.filter(c=>!ids.includes(c.id));assert.equal(old.length,18);assert.equal(createHash('sha256').update(JSON.stringify(old)).digest('hex'),'9751e0eb0a0fcf5b17f3947bc27af8be1ffd777628c64775779dc5f1b4c96209');});
test('batch six gives three original briefs exact catalogue and future dates without invented Predict links',()=>{assert.deepEqual(['2026-11-05','2026-11-07','2026-11-09'].map(d=>loop.lessonFor(d)),ids);for(const id of ids){assert.equal(e.challenges.filter(c=>c.id===id&&!c.reviewOnly).length,1);assert(!loop.connections[id]);}assert.equal(loop.schedules[3].order.length,18);assert.equal(loop.lessonFor('2026-11-04'),loop.schedules[3].order[17]);});
test('each new module has a required loader and all per-scene timelines validate',()=>{const html=fs.readFileSync(new URL('./index.html',import.meta.url),'utf8');for(const file of ['gold-daily-return-time.js','gold-daily-serve-quality.js','gold-daily-patterns.js'])assert(html.includes(file));assert(html.includes('withheld-missing-evidence'));assert.deepEqual(e.audit().errors,[]);});
test('serve reversal uses common capability and derives remaining reach',()=>{const s=require('./gold-daily-serve-quality.js'),m=[0,1,2,3].map(c=>s.model('serve_quality',2,c));assert(m.every(x=>x.movementSpeed===2.7&&x.reaction===.18));assert(m[1].movementSpeed*(m[1].receive-m[1].hit-m[1].reaction)<m[1].travel);assert(m[1].spacing>1);assert.equal(m[2].receiverFoot[0],m[2].idealFoot[0]);for(const x of m)assert.deepEqual(s.sample(x,x.receive).far,x.receiverFoot);});
test('surfaced batch six lessons require completed mobile and desktop review',()=>{const manifest=JSON.parse(fs.readFileSync(new URL('./LAUNCH_MANIFEST.json',import.meta.url),'utf8'));for(const id of ids){const entry=manifest.daily.additions.find(x=>x.id===id);assert(entry,'Missing review record: '+id);assert.equal(entry.mobileReview,'approved',id+' mobile');assert.equal(entry.desktopReview,'approved',id+' desktop');assert.equal(entry.approvalDate,'2026-09-14');}});
test('reduced serve reads retain four compact ungraded contact snapshots',()=>{const s=require('./gold-daily-serve-quality.js'),lesson=e.challenges.find(x=>x.id===ids[1]);for(const scene of [1,2]){const html=s.render(lesson.steps[scene],null,0,true);assert.equal((html.match(/class="gd-serve-contact-card"/g)||[]).length,4);assert(html.includes('gd-serve-contact-grid'));assert(!html.includes('gd-sequence-frame'));assert(!/correct|better choice|winner/i.test(html));}});
test('first RAF timestamps cannot select a negative history record',()=>{const p=require('./gold-daily-patterns.js'),lesson=e.challenges.find(x=>x.id===ids[2]);assert.equal(p.render(lesson.steps[1],null,-.015,false),p.render(lesson.steps[1],null,0,false));const source=fs.readFileSync(new URL('./gold-daily-prototypes.js',import.meta.url),'utf8');assert.equal((source.match(/Math\.min\(total,Math\.max\(0,\(now-started\)\/1000\)\)/g)||[]).length,2);});
