const LESSON={
  title:"Predict the Point: Break Point on a Second Serve",
  hook:"15-40. Their second serve is slow and sits up on your forehand. Read the point one ball at a time.",
  memHTML:"Find the corner, <span>then keep going back to it.</span>",
  tomorrow:"On a soft second serve, step in and go deep to one corner. When they scramble back, send the next ball to the corner they just left.",
  finaleScene:"ps3C", finaleFull:true,
  predict:{scene:"ps3C", reads:["ps1A","ps2A","ps3A"], askCam:{c:{az:-90,el:40,d:30,fov:36,tgt:[0,0.8,0]},phone:{az:-90,el:44,d:40,fov:24,tgt:[0,0.2,0]}}, intro:"Picture the whole point first", watch:"Now watch the point you pictured, played the best way.",
    says:["Deep to their backhand. They stretch for it and can only slice it short.","Back to the corner they just left. They sprint for it and can only float a pass.","Back to the same corner. They're still running the other way. Winner."]},
  cam0:{follow:true},
  redoLabel:"Play the point again",
  steps:[
   {ph:"Read 1 · The return",short:"Return",name:"Their second serve",scene:"ps1",
    sit:"15-40. A slow second serve sits up on your forehand. The server stays back.",
    q:"Where does your return go?",
    opts:["High and safe through the middle","Deep to their backhand corner","A short chip","Deep to their forehand corner"],
    correct:1,payoff:"Deep to the corner makes them stretch, and all they have is a short slice.",
    principle:"A soft second serve is a chance to make them run, not to hit a winner.",
    why:"Stepping in gives you time. Deep into a corner costs them a stretch; a safe ball through the middle or a short chip hands the server a free forehand.",
    rail:["1 Soft second serve","2 You step in","3 Server stays back"],
    cues:{ball:"SITS UP",you:"STEP IN",opp:"STAYS BACK"},
    unlock:"Make the server run",take:"Soft second serve? Step in and go deep to a corner.",
    lines:{A:"Safe and central — they step in; you're only just in time.",
      B:"Deep to the corner — they stretch and can only slice it short.",
      C:"Short — they step in and you're stretched for their reply.",
      D:"Deep, but they reach it and play the rally — you're in time."}},
   {ph:"Read 2 · The approach",short:"Approach",name:"Their short slice",scene:"ps2",
    sit:"Their stretched slice lands short. They're racing back toward the middle.",
    q:"Where do you go with this ball?",
    opts:["Through the middle, and follow it in","Into the open corner, and stay back","A drop shot","Deep to the corner they left, and follow it in"],
    correct:3,payoff:"Back where they came from, they sprint again and can only float a pass. You're at the net.",
    principle:"A short ball is an approach: send it where they're not heading, then come in.",
    why:"They're running to the middle. The corner they left makes them stop and turn back. Staying back gives them time to recover; the middle feeds them a pass.",
    rail:["1 Short slice","2 They run back","3 The corner they left"],
    cues:{ball:"SHORT SLICE",you:"STEP IN",opp:"RUNNING BACK"},
    unlock:"Come in behind it",take:"Short ball while they recover? Approach to the corner they left.",
    lines:{A:"Straight to them — they pass you.",
      B:"They reach it and the rally goes on — the chance is gone.",
      C:"They're coming forward anyway — they get it and pass you.",
      D:"They turn back, reach it and float a pass — you're set at the net."}},
   {ph:"Read 3 · The volley",short:"Volley",name:"Their pass",scene:"ps3",
    sit:"You're at the net. Their pass floats crosscourt. They're already heading back to the middle.",
    q:"Where do you volley it?",
    opts:["Into the open court","Deep through the middle","Back to the corner they hit from","A drop volley"],
    correct:2,alsoOk:[3],payoff:"They're running the other way and can't turn in time. Winner.",
    principle:"The open court is where a recovering player is running. Volley behind them.",
    why:"By the time you volley, they've started back to the middle, so the open court is on their way. The corner they left, or a drop volley short, is out of reach.",
    rail:["1 Their pass","2 They recover","3 Behind them"],
    cues:{ball:"FLOATING PASS",you:"AT THE NET",opp:"RECOVERING"},
    unlock:"Volley behind the runner",take:"At the net, volley to where they're coming from, not the open court.",
    lines:{A:"They're running that way — they get it and pass you.",
      B:"Right to them — they pass you.",
      C:"Behind them — they can't turn back in time. Winner.",
      D:"Short and soft — they're too deep to reach it. Winner too."}}
  ]
};
