const LESSON={
  title:"Predict the Point: The Wide Serve Pattern",
  hook:"30-30, deuce court. They stand close to the middle to protect their backhand. Read the point one ball at a time.",
  memHTML:"The serve sets up <span>the whole point.</span>",
  tomorrow:"Before you toss, look where they stand. If they guard the middle, serve wide and plan the +1.",
  finaleScene:"pt3D", finaleFull:true,
  predict:{scene:"pt3D", reads:[10,"pt2A","pt3A"], askCam:{c:{az:-90,el:40,d:30,fov:36,tgt:[0,0.8,0]},phone:{az:-90,el:44,d:40,fov:24,tgt:[0,0.2,0]}}, intro:"Picture the whole point first", watch:"Now watch the point you pictured, played the best way.",
    says:["You serve wide. They reach it outside the sideline and can only block a short ball back.","Into the open corner. They sprint across and can only float it back.","Behind them — they're still racing back and can't turn. Winner."]},
  cam0:{follow:true},
  redoLabel:"Play the point again",
  steps:[
   {ph:"Read 1 · The serve",short:"Serve",name:"Where do you serve?",scene:"pt1",
    sit:"30-30, deuce court. They crowd the middle to protect their backhand.",
    q:"Where do you serve to set up the point?",
    opts:["Down the T","Straight at them","Wide, to pull them off the court","A slower kick to the T"],
    correct:2,payoff:"The wide serve drags them off the court and they can only block it back.",
    principle:"A serve is the first shot of a pattern, not just a way to start the point.",
    why:"They stand close to the middle, so the T, the body and the kick all rush them without moving them. Only the wide serve drags them off the court and opens it for your next ball.",
    rail:["1 They guard the middle","2 Your serve","3 Their return"],
    cues:{ball:"YOUR SERVE",you:"SERVER",opp:"GUARDS MIDDLE"},
    unlock:"The serve opens the court",take:"They guard the middle? Serve wide and the court opens.",
    lines:{A:"A short ball back, but they're still in the middle of the court.",
      B:"At their body — rushed, but they're still in the middle.",
      C:"Wide — they're dragged off the court and block a short ball back.",
      D:"Rushed, but still central — no open court for you."}},
   {ph:"Read 2 · The +1",short:"+1",name:"The short ball",scene:"pt2",
    sit:"Say you served wide: they block a short ball back from outside the sideline and scramble back.",
    q:"Where does your +1 go?",
    opts:["Deep through the middle","Into the open corner","Back to where they hit from","A drop shot"],
    correct:1,payoff:"The open court makes them sprint — all they can send back is a float.",
    principle:"Hit the +1 into the space your serve created.",
    why:"They have to cover the width of the court at a sprint. Back to them or down the middle gives them the easy ball the serve took away.",
    rail:["1 Short ball","2 They scramble","3 Open court"],
    cues:{ball:"SHORT BALL",you:"STEP IN",opp:"SCRAMBLING"},
    unlock:"Punish the pattern",take:"The serve pulled them wide — send the +1 to the open court.",
    lines:{A:"Right to them — you're only just in time for their reply.",
      B:"They sprint, reach it, and can only float it back — you're set early.",
      C:"Straight back to them — you're in the rally, nothing more.",
      D:"From back here the drop sits up — they get it and you're stretched."}},
   {ph:"Read 3 · The finish",short:"Finish",name:"Their float",scene:"pt3",
    sit:"Your +1 went into the open corner. They float it back at a sprint and race back — not there yet.",
    q:"Where do you finish it?",
    opts:["Into the corner they're running to","Deep through the middle","A drop shot","Behind them, back where they came from"],
    correct:3,payoff:"Behind a player who is still running, the ball goes where they can't turn back to.",
    principle:"A recovering player can't change direction in time: hit behind them.",
    why:"They are already moving toward the empty corner. The ball behind them makes them stop and reverse, and there is no time for that.",
    rail:["1 Their float","2 They run back","3 Behind them"],
    cues:{ball:"FLOAT",you:"SET EARLY",opp:"RUNNING BACK"},
    unlock:"Wrong-foot the runner",take:"They're sprinting back? Hit behind them.",
    lines:{A:"They're running that way — they get it, but can only chip it short.",
      B:"Straight to them — you're only just in time.",
      C:"They're moving that way — they run it down and pass you.",
      D:"Behind them — they're still racing back and can't turn. Winner."}}
  ]
};
